name: hisabsaathi_mobile
description: Offline-first mobile client for HisabSaathi.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true