import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import dotenv from 'dotenv';
import rateLimit from 'express-rate-limit';
import { db } from './db.js';
import { authRequired, issueAccessToken, hashToken } from './auth.js';

dotenv.config();
const app=express();
const PORT=Number(process.env.PORT||3000);
const WEB=path.resolve(new URL('../web/',import.meta.url).pathname);
const UPLOAD_DIR=path.resolve(process.env.PAYMENT_UPLOAD_DIR||'./data/payment-proof');
fs.mkdirSync(UPLOAD_DIR,{recursive:true});
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:true}));app.use(express.json({limit:'10mb'}));app.use('/api',rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
const id=()=>crypto.randomUUID();const newProfile=()=>{let p;do{p='HS-'+crypto.randomBytes(4).toString('hex').toUpperCase();}while(db.prepare('SELECT 1 FROM shops WHERE profile_id=?').get(p));return p;};
const trialExpiry=s=>new Date(new Date(s.created_at+'Z').getTime()+86400000).toISOString();
function accessFor(s){const now=Date.now();if(s.subscription_status==='active'&&s.subscription_expires_at&&new Date(s.subscription_expires_at).getTime()>now)return {active:true,mode:'premium',expires_at:s.subscription_expires_at};if(s.subscription_status==='trial'&&new Date(trialExpiry(s)).getTime()>now)return {active:true,mode:'demo',expires_at:trialExpiry(s)};return {active:false,mode:'locked',expires_at:s.subscription_expires_at||trialExpiry(s)};}
function expire(){const now=new Date().toISOString();db.prepare("UPDATE shops SET subscription_status='expired',updated_at=CURRENT_TIMESTAMP WHERE subscription_status='active' AND subscription_expires_at IS NOT NULL AND subscription_expires_at<=?").run(now);}
function premium(req,res,next){expire();const s=db.prepare('SELECT * FROM shops WHERE id=?').get(req.shopId);if(!s)return res.status(401).json({error:'Shop not found'});const a=accessFor(s);if(!a.active)return res.status(402).json({error:'Premium subscription required',code:'PREMIUM_REQUIRED',subscription_status:s.subscription_status});req.access=a;next();}
function admin(req,res,next){const secret=process.env.ADMIN_VERIFY_SECRET;if(!secret||req.headers['x-admin-verify-secret']!==secret)return res.status(401).json({error:'Unauthorized'});next();}
function saveProof(data,orderId){const m=String(data||'').match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!m)throw new Error('Upload a valid image receipt');const ext=m[1]==='jpeg'?'jpg':m[1];const file=path.join(UPLOAD_DIR,`${orderId}.${ext}`);fs.writeFileSync(file,Buffer.from(m[2],'base64'),{mode:0o600});return file;}
async function notifyOwner(payload,proofPath){const token=process.env.WHATSAPP_TOKEN,phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID,to=process.env.ADMIN_WHATSAPP_TO||'916206769679';if(!token||!phoneId)return false;try{const base=`https://graph.facebook.com/${process.env.WHATSAPP_API_VERSION||'v23.0'}/${phoneId}`;const text=`HisabSaathi payment claim\nProfile: ${payload.profile_id}\nShop: ${payload.shop_name}\nAmount: ₹149\nUTR: ${payload.utr}\nOrder: ${payload.order_id}\nVerify actual payment before approval.`;const r=await fetch(`${base}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body:text}})});if(!r.ok)return false;if(proofPath&&fs.existsSync(proofPath)){const form=new FormData();form.append('messaging_product','whatsapp');form.append('file',new Blob([fs.readFileSync(proofPath)],{type:'image/jpeg'}),'receipt.jpg');const u=await fetch(`${base}/media`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});const j=await u.json();if(u.ok&&j.id)await fetch(`${base}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'image',image:{id:j.id,caption:`Receipt • ${payload.profile_id} • UTR ${payload.utr}`}})});}return true;}catch{return false;}}
app.get('/api/health',(_q,r)=>r.json({ok:true,service:'HisabSaathi',time:new Date().toISOString()}));
app.post('/api/shops',(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)throw new Error('Shop name is required');const sid=id(),token=issueAccessToken(),profile=newProfile();db.prepare(`INSERT INTO shops(id,name,address,category,owner_name,language,subscription_status,profile_id,access_token_hash) VALUES(?,?,?,?,?,?,?,?,?)`).run(sid,name,String(req.body.address||''),String(req.body.category||''),String(req.body.owner_name||''),String(req.body.language||'hi'),'trial',profile,hashToken(token));res.status(201).json({shop:db.prepare('SELECT * FROM shops WHERE id=?').get(sid),access_token:token});}catch(e){res.status(400).json({error:e.message});}});
app.use('/api',authRequired);
app.get('/api/me',(req,res)=>{expire();const s=db.prepare('SELECT * FROM shops WHERE id=?').get(req.shopId);res.json({shop:s,access:accessFor(s)});});
app.get('/api/subscriptions/status',(req,res)=>{expire();const s=db.prepare('SELECT * FROM shops WHERE id=?').get(req.shopId);res.json({subscription:{status:s.subscription_status,expires_at:s.subscription_expires_at,profile_id:s.profile_id},access:accessFor(s)});});
app.patch('/api/shop',(req,res)=>{const keys=['name','address','category','owner_name','language'];const used=keys.filter(k=>req.body[k]!==undefined);if(used.length)db.prepare(`UPDATE shops SET ${used.map(k=>`${k}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...used.map(k=>req.body[k]),req.shopId);res.json({shop:db.prepare('SELECT * FROM shops WHERE id=?').get(req.shopId)});});
app.post('/api/subscriptions/order',(req,res)=>{const oid=id(),exp=new Date(Date.now()+86400000).toISOString();db.prepare(`INSERT INTO subscription_orders(id,shop_id,provider,amount,currency,status,expires_at) VALUES(?,?,?,?,?,?,?)`).run(oid,req.shopId,'upi_manual',14900,'INR','created',exp);res.status(201).json({order_id:oid,amount:149,currency:'INR',upi_id:'6206769679@nyes',expires_at:exp,profile_id:db.prepare('SELECT profile_id FROM shops WHERE id=?').get(req.shopId).profile_id});});
app.post('/api/subscriptions/claim',async(req,res)=>{try{const order=db.prepare('SELECT o.*,s.profile_id,s.name AS shop_name,s.owner_name FROM subscription_orders o JOIN shops s ON s.id=o.shop_id WHERE o.id=? AND o.shop_id=?').get(req.body.order_id,req.shopId);if(!order)throw new Error('Payment order not found');if(new Date(order.expires_at)<new Date())throw new Error('Payment order expired. Create a new payment order.');const utr=String(req.body.utr||'').trim();if(utr.length<6)throw new Error('UTR is required');const dup=db.prepare("SELECT id FROM subscription_orders WHERE provider_ref=? AND id<>? AND status IN ('pending_verification','paid')").get(utr,order.id);if(dup)throw new Error('This UTR is already used');const proof=saveProof(req.body.screenshot_data_url,order.id);db.prepare("UPDATE subscription_orders SET status='pending_verification',provider_ref=?,proof_path=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(utr,proof,order.id);db.prepare("UPDATE shops SET subscription_status='pending_verification',updated_at=CURRENT_TIMESTAMP WHERE id=? AND subscription_status<>'active'").run(req.shopId);const payload={order_id:order.id,profile_id:order.profile_id,shop_id:req.shopId,shop_name:order.shop_name,owner_name:order.owner_name,utr};await notifyOwner(payload,proof);res.json({status:'pending_verification',profile_id:order.profile_id,message:'Receipt submitted. Premium starts only after payment verification.'});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/customers',premium,(req,res)=>res.json({customers:db.prepare('SELECT * FROM customers WHERE shop_id=? ORDER BY name').all(req.shopId)}));
app.post('/api/customers',premium,(req,res)=>{try{const name=String(req.body.name||'').trim(),phone=String(req.body.phone||'').trim();if(!name||!phone)throw new Error('Customer name and phone number are required');const c=id(),balance=Math.max(0,Math.round(Number(req.body.opening_udhaar||0)*100));db.prepare(`INSERT INTO customers(id,shop_id,name,phone,address,credit_balance,due_date) VALUES(?,?,?,?,?,?,?)`).run(c,req.shopId,name,phone,String(req.body.address||''),balance,req.body.due_date||null);if(req.body.auto_reminder)db.prepare(`INSERT INTO reminders(id,shop_id,customer_id,channel,scheduled_for) VALUES(?,?,?,?,?)`).run(id(),req.shopId,c,'whatsapp',new Date().toISOString());res.status(201).json({customer:db.prepare('SELECT * FROM customers WHERE id=?').get(c)});}catch(e){res.status(400).json({error:e.message});}});
app.patch('/api/customers/:id',premium,(req,res)=>{const c=db.prepare('SELECT * FROM customers WHERE id=? AND shop_id=?').get(req.params.id,req.shopId);if(!c)return res.status(404).json({error:'Customer not found'});const allowed=['name','phone','address','due_date'],used=allowed.filter(k=>req.body[k]!==undefined);if(used.length)db.prepare(`UPDATE customers SET ${used.map(k=>`${k}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...used.map(k=>req.body[k]),c.id);res.json({customer:db.prepare('SELECT * FROM customers WHERE id=?').get(c.id)});});
app.post('/api/customers/:id/payment',premium,(req,res)=>{const c=db.prepare('SELECT * FROM customers WHERE id=? AND shop_id=?').get(req.params.id,req.shopId);if(!c)return res.status(404).json({error:'Customer not found'});const amount=Math.max(0,Math.round(Number(req.body.amount||0)*100));if(!amount)return res.status(400).json({error:'Amount required'});const next=Math.max(0,c.credit_balance-amount);db.prepare('UPDATE customers SET credit_balance=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(next,c.id);db.prepare(`INSERT INTO payments(id,shop_id,customer_id,amount,method,status) VALUES(?,?,?,?,?,?)`).run(id(),req.shopId,c.id,amount,String(req.body.method||'cash'),'paid');res.json({customer:db.prepare('SELECT * FROM customers WHERE id=?').get(c.id)});});
app.get('/api/products',premium,(req,res)=>res.json({products:db.prepare('SELECT * FROM products WHERE shop_id=? ORDER BY name').all(req.shopId)}));
app.post('/api/products',premium,(req,res)=>{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Product name required'});const p=id();db.prepare(`INSERT INTO products(id,shop_id,name,sku,price,stock,low_stock_threshold) VALUES(?,?,?,?,?,?,?)`).run(p,req.shopId,name,String(req.body.sku||''),Math.round(Number(req.body.price||0)*100),Math.max(0,Number(req.body.stock||0)),Math.max(0,Number(req.body.low_stock_threshold||5)));res.status(201).json({product:db.prepare('SELECT * FROM products WHERE id=?').get(p)});});
app.post('/api/invoices',premium,(req,res)=>{try{const items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)throw new Error('At least one item is required');const total=items.reduce((s,x)=>s+Math.round(Number(x.qty||0)*Number(x.unit_price||0)*100),0),paid=Math.min(total,Math.round(Number(req.body.paid||0)*100)),credit=total-paid,inv=id();db.prepare(`INSERT INTO invoices(id,shop_id,customer_id,invoice_no,subtotal,paid,credit,status) VALUES(?,?,?,?,?,?,?,?)`).run(inv,req.shopId,req.body.customer_id||null,String(req.body.invoice_no||Date.now()),total,paid,credit,credit?'credit':'paid');const ins=db.prepare(`INSERT INTO invoice_items(id,invoice_id,product_id,name,qty,unit_price,amount) VALUES(?,?,?,?,?,?,?)`);for(const x of items)ins.run(id(),inv,x.product_id||null,String(x.name),Number(x.qty),Math.round(Number(x.unit_price)*100),Math.round(Number(x.qty)*Number(x.unit_price)*100));if(req.body.customer_id&&credit)db.prepare('UPDATE customers SET credit_balance=credit_balance+?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND shop_id=?').run(credit,req.body.customer_id,req.shopId);res.status(201).json({invoice:db.prepare('SELECT * FROM invoices WHERE id=?').get(inv),total:total/100,credit:credit/100});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/dashboard',premium,(req,res)=>{const customers=db.prepare('SELECT COUNT(*) c FROM customers WHERE shop_id=?').get(req.shopId).c,products=db.prepare('SELECT COUNT(*) c FROM products WHERE shop_id=?').get(req.shopId).c,due=db.prepare('SELECT COALESCE(SUM(credit_balance),0) s FROM customers WHERE shop_id=?').get(req.shopId).s,sales=db.prepare("SELECT COALESCE(SUM(subtotal),0) s FROM invoices WHERE shop_id=? AND created_at>=date('now','start of month')").get(req.shopId).s;res.json({customers,products,udhaar:due/100,sales:sales/100});});
app.get('/api/admin/stats',admin,(req,res)=>{res.json({users:db.prepare('SELECT COUNT(*) c FROM shops').get().c,premium:db.prepare("SELECT COUNT(*) c FROM shops WHERE subscription_status='active'").get().c,pending_payments:db.prepare("SELECT COUNT(*) c FROM subscription_orders WHERE status='pending_verification'").get().c,customers:db.prepare('SELECT COUNT(*) c FROM customers').get().c});});
app.get('/api/admin/profiles',admin,(req,res)=>res.json({profiles:db.prepare('SELECT profile_id,name,owner_name,subscription_status,subscription_expires_at,created_at FROM shops ORDER BY created_at DESC').all()}));
app.get('/api/admin/payments',admin,(req,res)=>res.json({payments:db.prepare(`SELECT o.*,s.profile_id,s.name shop_name,s.owner_name FROM subscription_orders o JOIN shops s ON s.id=o.shop_id ORDER BY o.created_at DESC LIMIT 200`).all()}));
app.get('/api/admin/payments/:id/proof',admin,(req,res)=>{const r=db.prepare('SELECT proof_path FROM subscription_orders WHERE id=?').get(req.params.id);if(!r?.proof_path||!fs.existsSync(r.proof_path))return res.status(404).end();res.sendFile(path.resolve(r.proof_path));});
app.post('/api/admin/payments/:id/verify',admin,(req,res)=>{const o=db.prepare('SELECT * FROM subscription_orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(req.body.approved){const exp=new Date(Date.now()+30*86400000).toISOString();db.prepare("UPDATE subscription_orders SET status='paid',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(o.id);db.prepare("UPDATE shops SET subscription_status='active',subscription_expires_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(exp,o.shop_id);return res.json({status:'paid',expires_at:exp});}db.prepare("UPDATE subscription_orders SET status='rejected',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(o.id);db.prepare("UPDATE shops SET subscription_status='suspended',subscription_expires_at=NULL WHERE id=?").run(o.shop_id);res.json({status:'rejected'});});
app.post('/api/admin/profiles/:profileId/disable',admin,(req,res)=>{const r=db.prepare('SELECT id FROM shops WHERE profile_id=?').get(req.params.profileId);if(!r)return res.status(404).json({error:'Profile not found'});db.prepare("UPDATE shops SET subscription_status='suspended',subscription_expires_at=NULL WHERE id=?").run(r.id);res.json({status:'disabled'});});
app.post('/api/admin/profiles/:profileId/activate',admin,(req,res)=>{const r=db.prepare('SELECT id FROM shops WHERE profile_id=?').get(req.params.profileId);if(!r)return res.status(404).json({error:'Profile not found'});const exp=new Date(Date.now()+30*86400000).toISOString();db.prepare("UPDATE shops SET subscription_status='active',subscription_expires_at=? WHERE id=?").run(exp,r.id);res.json({status:'active',expires_at:exp});});
app.use(express.static(WEB));app.get('*',(_q,r)=>r.sendFile(path.join(WEB,'index.html')));app.listen(PORT,()=>console.log(`HisabSaathi listening on ${PORT}`));